
-- First, let's see what countries currently exist
SELECT name, code FROM countries ORDER BY name;

-- Add African countries to the countries table
INSERT INTO countries (name, code, flag_emoji, timezone) VALUES
('Algeria', 'DZ', '🇩🇿', 'Africa/Algiers'),
('Angola', 'AO', '🇦🇴', 'Africa/Luanda'),
('Benin', 'BJ', '🇧🇯', 'Africa/Porto-Novo'),
('Botswana', 'BW', '🇧🇼', 'Africa/Gaborone'),
('Burkina Faso', 'BF', '🇧🇫', 'Africa/Ouagadougou'),
('Burundi', 'BI', '🇧🇮', 'Africa/Bujumbura'),
('Cameroon', 'CM', '🇨🇲', 'Africa/Douala'),
('Cape Verde', 'CV', '🇨🇻', 'Atlantic/Cape_Verde'),
('Central African Republic', 'CF', '🇨🇫', 'Africa/Bangui'),
('Chad', 'TD', '🇹🇩', 'Africa/Ndjamena'),
('Comoros', 'KM', '🇰🇲', 'Indian/Comoro'),
('Democratic Republic of the Congo', 'CD', '🇨🇩', 'Africa/Kinshasa'),
('Republic of the Congo', 'CG', '🇨🇬', 'Africa/Brazzaville'),
('Djibouti', 'DJ', '🇩🇯', 'Africa/Djibouti'),
('Egypt', 'EG', '🇪🇬', 'Africa/Cairo'),
('Equatorial Guinea', 'GQ', '🇬🇶', 'Africa/Malabo'),
('Eritrea', 'ER', '🇪🇷', 'Africa/Asmara'),
('Eswatini', 'SZ', '🇸🇿', 'Africa/Mbabane'),
('Ethiopia', 'ET', '🇪🇹', 'Africa/Addis_Ababa'),
('Gabon', 'GA', '🇬🇦', 'Africa/Libreville'),
('Gambia', 'GM', '🇬🇲', 'Africa/Banjul'),
('Ghana', 'GH', '🇬🇭', 'Africa/Accra'),
('Guinea', 'GN', '🇬🇳', 'Africa/Conakry'),
('Guinea-Bissau', 'GW', '🇬🇼', 'Africa/Bissau'),
('Ivory Coast', 'CI', '🇨🇮', 'Africa/Abidjan'),
('Kenya', 'KE', '🇰🇪', 'Africa/Nairobi'),
('Lesotho', 'LS', '🇱🇸', 'Africa/Maseru'),
('Liberia', 'LR', '🇱🇷', 'Africa/Monrovia'),
('Libya', 'LY', '🇱🇾', 'Africa/Tripoli'),
('Madagascar', 'MG', '🇲🇬', 'Indian/Antananarivo'),
('Malawi', 'MW', '🇲🇼', 'Africa/Blantyre'),
('Mali', 'ML', '🇲🇱', 'Africa/Bamako'),
('Mauritania', 'MR', '🇲🇷', 'Africa/Nouakchott'),
('Mauritius', 'MU', '🇲🇺', 'Indian/Mauritius'),
('Morocco', 'MA', '🇲🇦', 'Africa/Casablanca'),
('Mozambique', 'MZ', '🇲🇿', 'Africa/Maputo'),
('Namibia', 'NA', '🇳🇦', 'Africa/Windhoek'),
('Niger', 'NE', '🇳🇪', 'Africa/Niamey'),
('Nigeria', 'NG', '🇳🇬', 'Africa/Lagos'),
('Rwanda', 'RW', '🇷🇼', 'Africa/Kigali'),
('São Tomé and Príncipe', 'ST', '🇸🇹', 'Africa/Sao_Tome'),
('Senegal', 'SN', '🇸🇳', 'Africa/Dakar'),
('Seychelles', 'SC', '🇸🇨', 'Indian/Mahe'),
('Sierra Leone', 'SL', '🇸🇱', 'Africa/Freetown'),
('Somalia', 'SO', '🇸🇴', 'Africa/Mogadishu'),
('South Africa', 'ZA', '🇿🇦', 'Africa/Johannesburg'),
('South Sudan', 'SS', '🇸🇸', 'Africa/Juba'),
('Sudan', 'SD', '🇸🇩', 'Africa/Khartoum'),
('Tanzania', 'TZ', '🇹🇿', 'Africa/Dar_es_Salaam'),
('Togo', 'TG', '🇹🇬', 'Africa/Lome'),
('Tunisia', 'TN', '🇹🇳', 'Africa/Tunis'),
('Uganda', 'UG', '🇺🇬', 'Africa/Kampala'),
('Zambia', 'ZM', '🇿🇲', 'Africa/Lusaka'),
('Zimbabwe', 'ZW', '🇿🇼', 'Africa/Harare')
ON CONFLICT (code) DO NOTHING;
